### ISSUE TITLE
com.ctc.wstx.exc.WstxParsingException:

### ISSUE THREAD

**Issue by jieryn** [mojohaus/tidy-maven-plugin#7]
Taking a failure during tidy:pom and tidy:check. The line specified, 2766 is actually the end of file.

```
[ERROR] Failed to execute goal org.codehaus.mojo:tidy-maven-plugin:1.0.0:check (default-cli) on project base: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
[ERROR] at [row,col {unknown-source}]: [2766,7]
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:tidy-maven-plugin:1.0.0:check (default-cli) on project base: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
 at [row,col {unknown-source}]: [2766,7]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.MojoExecutionException: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
 at [row,col {unknown-source}]: [2766,7]
        at org.codehaus.mojo.tidy.TidyMojo.tidy(TidyMojo.java:106)
        at org.codehaus.mojo.tidy.CheckMojo.executeForPom(CheckMojo.java:39)
        at org.codehaus.mojo.tidy.TidyMojo.execute(TidyMojo.java:67)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 11 more
Caused by: com.ctc.wstx.exc.WstxParsingException: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
 at [row,col {unknown-source}]: [2766,7]
        at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:580)
        at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:453)
        at com.ctc.wstx.sr.BasicStreamReader.readPIPrimary(BasicStreamReader.java:3877)
        at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2017)
        at com.ctc.wstx.sr.BasicStreamReader.closeContentTree(BasicStreamReader.java:2858)
        at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2609)
        at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1054)
        at org.codehaus.stax2.ri.Stax2EventReaderImpl.nextEvent(Stax2EventReaderImpl.java:255)
        at org.codehaus.mojo.tidy.task.EnsureOrderAndIndent$SectionSorter.sortSections(EnsureOrderAndIndent.java:117)
        at org.codehaus.mojo.tidy.task.EnsureOrderAndIndent.tidyPom(EnsureOrderAndIndent.java:78)
        at org.codehaus.mojo.tidy.task.PomTidy.tidy(PomTidy.java:44)
        at org.codehaus.mojo.tidy.TidyMojo.tidy(TidyMojo.java:102)
        ... 15 more

```

I was able to figure out what in my pom.xml is causing this, it's build > pluginManagement > plugins >

```
        <plugin>
          <groupId>org.apache.openejb.maven</groupId>
          <artifactId>tomee-maven-plugin</artifactId>
          <configuration>
            <synchronization>
              <extensions>
                <extension>.class</extension>   
                <extension>.css</extension>
                <extension>.html</extension>
                <extension>.js</extension>
                <extension>.ui.xml</extension>
              </extensions>
            </synchronization>
          </configuration>
        </plugin>

```

Falling back to 1.0-beta-1 lets tidy:pom work again.

**Comment by awhitford** [comment]
+1

Running into this problem too.  The `check` goal is failing, so figure running `pom` goal will *fix* the issue -- alas, that produces the exception too, so I'm stuck and unable to upgrade.

**Comment by dennisl** [comment]
We stumbled across this as well with the following POM snippet. The error occurs on the `<extension>` line. This is consistent with the error that @jieryn got. It seems that the tag `<extension>` somehow trips up the XML parser.

```xml
      <plugin>
        <groupId>org.apache.cxf</groupId>
        <artifactId>cxf-xjc-plugin</artifactId>
        <version>3.0.5</version>
        <configuration>
          <extensions>
            <!-- Getters with default values if given in schema -->
            <extension>org.apache.cxf.xjcplugins:cxf-xjc-dv:3.0.5</extension>
          </extensions>
        </configuration>
        <executions>
          ...
        </executions>
      </plugin>
```

**Comment by andham** [comment]
I'm also seeing this when executing tidy:pom on a project using the jaxb2-maven-plugin, where <extension> parameter is configured for that plugin.

**Comment by andham** [comment]
The problem lies in that we have code to sort <extension> sections in the pom, which expects a certain structure which isn't fullfilled here.

**Comment by andham** [comment]
Should be fixed by PR #13.

**Comment by tchemit** [comment]
I got this error on this [pom](https://gitlab.com/ultreiaio/pom/raw/develop/pom.xml).
I will try which pom section provoque this error.

**Comment by andrewswan** [comment]
I'm also getting this error, I've narrowed it down to having a non-empty `<dependenciesToScan>` element in the configuration of an execution of the `maven-surefire-plugin` (a pretty common plugin). I'll put together a minimal POM that demonstrates the problem.

**Comment by onacit** [comment]
I'm still seeing this error with `1.1.0`. Any updates?

**Comment by dlakatos847** [comment]
In my case, an empty `<build />` tag caused this exception:

```
Caused by: com.ctc.wstx.exc.WstxParsingException: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
 at [row,col {unknown-source}]: [97,7]
    at com.ctc.wstx.sr.StreamScanner.constructWfcException (StreamScanner.java:621)
    at com.ctc.wstx.sr.StreamScanner.throwParseError (StreamScanner.java:491)
    at com.ctc.wstx.sr.BasicStreamReader.readPIPrimary (BasicStreamReader.java:4019)
    at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog (BasicStreamReader.java:2141)
    at com.ctc.wstx.sr.BasicStreamReader.closeContentTree (BasicStreamReader.java:2991)
    at com.ctc.wstx.sr.BasicStreamReader.nextFromTree (BasicStreamReader.java:2734)
    at com.ctc.wstx.sr.BasicStreamReader.next (BasicStreamReader.java:1123)
    at org.codehaus.stax2.ri.Stax2EventReaderImpl.nextEvent (Stax2EventReaderImpl.java:255)
    at org.codehaus.mojo.tidy.task.EnsureOrderAndIndent$SectionSorter.sortSections (EnsureOrderAndIndent.java:110)
    at org.codehaus.mojo.tidy.task.EnsureOrderAndIndent.tidyPom (EnsureOrderAndIndent.java:71)
    at org.codehaus.mojo.tidy.task.PomTidy.tidy (PomTidy.java:44)
    at org.codehaus.mojo.tidy.TidyMojo.tidy (TidyMojo.java:113)
    at org.codehaus.mojo.tidy.PomMojo.executeForPom (PomMojo.java:43)
    at org.codehaus.mojo.tidy.TidyMojo.execute (TidyMojo.java:78)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

Removing the `<build />` line solved my issue. I hope this helps others too.

**Comment by pzygielo** [comment]
> I got this error on this [pom](https://gitlab.com/ultreiaio/pom/raw/develop/pom.xml).
> I will try which pom section provoque this error.

I suppose following happens: elements (like properties) that (at least) end in `dependency`:
https://github.com/mojohaus/tidy-maven-plugin/blob/191b53ea4a06f9f6f0aa524355560d5d23fe716a/src/main/java/org/codehaus/mojo/tidy/task/EnsureOrderAndIndent.java#L56
or `plugin`:
https://github.com/mojohaus/tidy-maven-plugin/blob/191b53ea4a06f9f6f0aa524355560d5d23fe716a/src/main/java/org/codehaus/mojo/tidy/task/EnsureOrderAndIndent.java#L61
are then in
https://github.com/mojohaus/tidy-maven-plugin/blob/191b53ea4a06f9f6f0aa524355560d5d23fe716a/src/main/java/org/codehaus/mojo/tidy/task/EnsureOrderAndIndent.java#L138
improperly confirmed to be `startElementOfScope`, and then in
https://github.com/mojohaus/tidy-maven-plugin/blob/191b53ea4a06f9f6f0aa524355560d5d23fe716a/src/main/java/org/codehaus/mojo/tidy/task/EnsureOrderAndIndent.java#L113-L119
they result in malformed local `tidyPom`.
For example from `pom` linked above, should it be modified to
```
    <!--can't use plugin.version.plugin, break tidy plugin execution-->
    <!--See https://github.com/mojohaus/tidy-maven-plugin/issues/7-->
    <plugin.version.plugin>3.6.0</plugin.version.plugin>
```
tidy would produce `tidyPom` with content:
```xml
...
<properties>
...
    <plugin.version.plugin>3.6.0
    <plugin.version.plugin>3.6.0</plugin.version.plugin>
```
with unclosed `plugin.version.plugin` and its duplicate, and finally exception would be risen on next https://github.com/mojohaus/tidy-maven-plugin/blob/191b53ea4a06f9f6f0aa524355560d5d23fe716a/src/main/java/org/codehaus/mojo/tidy/task/EnsureOrderAndIndent.java#L109

----

I think it also applies to @andrewswan's case of 

>                 <configuration>
>                     <dependenciesToScan>
>                     	
>                         <dependency>foo:bar</dependency>
>                     </dependenciesToScan>

as `dependency` here, not being regular dependency section probably triggers the same.

**Comment by ddonahue1** [comment]
I received a similar problem using tidy pom version 1.1.0.  When I backed up to 1.0-beta-1, it told me to run mvn tidy:pom and then it worked.

**Comment by onacit** [comment]
Same here, Not `1.1.0`, nor `1.0.0`, but `1.0-beta-1` works.

**Comment by kasingal** [comment]
Is anobody working on to fix same ?

**Comment by pzygielo** [comment]
I believe this could be closed as fixed by
- #51

and its milestone updated to 1.2.0.

**Comment by jafarre-bi** [comment]
Also reproducible with version 1.3.0 when using the enforcer plugin rule "requireSameVersions" applied to dependencies. For instance:

>                 <plugin>
>                     <artifactId>maven-enforcer-plugin</artifactId>
>                     <version>..........</version>
>                     <configuration>
>                         <rules>
>                             <requireSameVersions>
>                                 <dependencies>
>                                     <dependency>......</dependency>
>                                 </dependencies>
>                             </requireSameVersions>
>                         </rules>
>                     </configuration>
>                 </plugin>

**Comment by pzygielo** [comment]
> Also reproducible with version 1.3.0 when using the enforcer plugin rule "requireSameVersions" applied to dependencies. For instance:
> 
> > ```xml
> >                                 <dependency>${some.group}</dependency>
> > ```

Like in https://github.com/mojohaus/tidy-maven-plugin/issues/7#issuecomment-522266699 - it's about `<dependency>` being named hmmm... _dependency_... 
- Summary of #51 suggests the fix was only for properties, not other elements named _dependency_ and not being one.
